### PR TITLE
Update to Android API 27 #72

### PR DESCRIPTION
**Pull request by ripern**
PR for issue #72

### CODE REVIEW

**Comment by cooperka** [comment]
Hi @ripern, thanks for the contribution. Is there any specific reason for this upgrade? In general, I don't like updating dependencies like this because it's hard to know what it might break on other people's apps. If there's a clear benefit, though, I'm willing to test it out.

**Comment by cooperka** [comment]
@masteralb, I see you've reacted a few times to this PR. Can you explain why you'd like this merged? It's not clear to me what the benefit might be. If anyone has a good reason, I'm happy to re-open and merge.

**Comment by masteralb** [comment]
@cooperka, i'm using this on my project. With current configuration i can't compile. #72 has fixed the compile errors. Thank you.

**Comment by cooperka** [comment]
Hmm, that's strange. Any chance you can post the original error you were seeing?

**Pull request closed without merging**
