### PR TITLE
Add ‘dismiss’ method to SnackBar

### PR DESCRIPTION
**Pull request by adnbsr**
`SnackBar.dismiss()` to solve [#8](https://github.com/cooperka/react-native-snackbar/issues/8)

### CODE REVIEW

**Review by cooperka — CHANGES_REQUESTED** [review]
Thanks for this, @adnbsr! My only request is that you call it `dismissAll` (because `dismiss` sounds like something that would be called on a particular snackbar instance, rather than statically). I'll try to test/merge soon.

**Comment by adnbsr** [comment]
That is right. Existing code includes singleton pattern, for this reason I just wanted to fix dismiss for one. To implement `dismissAll`, module should be restructured.

**Review by cooperka — APPROVED** [review]
I've added some logic to clear out the list of Snackbars so it doesn't grow infinitely, and the rest LGTM. Tested and verified. Thank you again @adnbsr, and apologies for the delay merging this!

**Comment by cooperka** [comment]
Released in https://github.com/cooperka/react-native-snackbar/releases/tag/v0.4.0.

**Comment by Noitidart** [comment]
Thank you folks!! I needed this!

**Pull request merged**
