### PR TITLE
update typescript definition to match export

### LINKED ISSUE #104: index.d.ts provides wong information
the structure in the index.d.ts (type definitions) imply that the lib must be imported by:

`import * as Snackbar from 'react-native-snackbar';`

but instead it provides a default export that contains the mentioned functions. meaning the above statement would then require calls like `Snackbar.Snackbar.show(...)`

so the file would have to include:

```ts
interface Snackbar{
  LENGTH_SHORT: number;
  LENGTH_LONG: number;
  LENGTH_INDEFINITE: number;

  show(options: SnackBarOptions): void;
  dismiss(): void;
}

export default Snackbar;
```

### PR DESCRIPTION
**Pull request by wodka**
fixes #104

### CODE REVIEW

**Comment by slavikdenis** [comment]
@wodka Are you sure this was a good idea?

Now, after the release TS is broken. I got
`'Snackbar' only refers to a type, but is being used as a value here.`
when using:

image

image

Also `SnackBarOptions` is not exported in the new version.

@cooperka should I create an issue ? I think the old typings were correct.

**Comment by wodka** [comment]
Strange - for me this release (just updated to 1.0.0) enables the types to work properly.

**Comment by slavikdenis** [comment]
Well, I guess I will just override the typings to the old one if nobody else have this problem. Strange world :D

**Comment by prtkkmrsngh** [comment]
@slavikdenis @wodka Yes I'm also facing same problem after upgrading to v1.0.0!

**Comment by wodka** [comment]
do you have a small example file with the broken import that fails with the types?

**Comment by slavikdenis** [comment]
For example, I use a wrapper like this:
```
import Snackbar, { SnackBarOptions } from 'react-native-snackbar';

// Original snackbar
type SnackCustomOptions = Pick<SnackBarOptions, 'duration'>;

// Custom snackbar
interface MessageStyle {
  color: string;
  backgroundColor: string;
}

interface MessageOptions extends SnackCustomOptions {
  text: string;
  type?: 'default' | 'success' | 'warning' | 'danger';
  buttonText?: string;
  onClose?: () => void;
}

// Message lengths
export const SHORT_MSG = Snackbar.LENGTH_SHORT; // cca 1 sec
export const LONG_MSG = Snackbar.LENGTH_LONG; // cca 3 sec
export const INF_MSG = Snackbar.LENGTH_INDEFINITE; // until button press

// Message styles
const MessageCommonStyle = {
  color: '#FFFFFF',
};

const MessageDefaultStyle: MessageStyle = {
  ...MessageCommonStyle,
  backgroundColor: 'rgba(0,0,0,0.8)',
};

const MessageSuccessStyle: MessageStyle = {
  ...MessageCommonStyle,
  backgroundColor: '#5cb85c',
};

const MessageWarningStyle: MessageStyle = {
  ...MessageCommonStyle,
  backgroundColor: '#f0ad4e',
};

const MessageDangerStyle: MessageStyle = {
  ...MessageCommonStyle,
  backgroundColor: '#d9534f',
};

// Message
export const showMessage = (opts: MessageOptions) => {
  // Default options
  const { type, text, duration, buttonText, onClose }: MessageOptions = {
    ...opts,
    duration: opts.duration === undefined ? LONG_MSG : opts.duration,
    type: opts.type === undefined ? 'default' : opts.type,
    buttonText: opts.buttonText === undefined ? 'OK' : opts.buttonText,
  };

  // Message style
  let msgStyle: MessageStyle = MessageDefaultStyle;

  if (type === 'success') {
    msgStyle = MessageSuccessStyle;
  } else if (type === 'warning') {
    msgStyle = MessageWarningStyle;
  } else if (type === 'danger') {
    msgStyle = MessageDangerStyle;
  }

  // onClose flag
  let didRunOnClose = false;

  // Show message
  Snackbar.show({
    title: text,
    duration: duration,
    color: msgStyle.color,
    backgroundColor: msgStyle.backgroundColor,
    action: {
      color: msgStyle.color,
      title: buttonText!,
      onPress: () => {
        Snackbar.dismiss();
        if (onClose && !didRunOnClose) {
          didRunOnClose = true;
          onClose();
        }
      },
    },
  });

  // Run onClose if button was not pressed
  if ((duration === SHORT_MSG || duration === LONG_MSG) && onClose) {
    const timeout = duration === SHORT_MSG ? 1000 : 3000;

    setTimeout(() => {
      if (!didRunOnClose) {
        didRunOnClose = true;
        onClose();
      }
    }, timeout);
  }
};
```

**Comment by ghost** [comment]
```ts
declare module 'react-native-snackbar' {
  // Type definitions for react-native-snackbar 0.3.4
  // Project: https://github.com/cooperka/react-native-snackbar
  // Definitions by: Kyle Roach <https://github.com/iRoachie>
  // TypeScript Version: 2.2.2

  /**
   * An actionable button that can be shown on the Snackbar.
   */
  interface Action {
    /**
     * Text for the button.
     */
    title: string

    /**
     * Color of the text for the button.
     * Accepts various forms of colors such as hex, literals, rgba, etc.
     */
    color?: string | number

    /**
     * Function called when the user presses the button.
     */
    onPress?(): void
  }

  /**
   * List of options to configure the Snackbar.
   */
  interface SnackBarOptions {
    /**
     * The text that appears on the Snackbar.
     */
    title: string

    /**
     * Color of the Snackbar title.
     * Accepts various forms of colors such as hex, literals, rgba, etc.
     */
    color?: string | number

    /**
     * Length of time the Snackbar stays on screen.
     * Must be one of Snackbar.LENGTH_SHORT, Snackbar.LENGTH_LONG, or Snackbar.LENGTH_INDEFINITE.
     */
    duration?: number

    /**
     * Background color of the snackbar
     * Accepts color strings such as hex, literals, rgba
     */
    backgroundColor?: string

    /**
     * Adds an actionable button to the snackbar on the right
     */
    action?: Action
  }

  /**
   * Snackbar definition
   */
  interface Snackbar {
    /**
     * Snackbar duration of about a second.
     */
    LENGTH_SHORT: number

    /**
     * Snackbar duration of about three seconds.
     */
    LENGTH_LONG: number

    /**
     * Snackbar duration that lasts forever (until a new Snackbar is shown).
     */
    LENGTH_INDEFINITE: number

    /**
     * Shows a native Snackbar component.
     *
     * @param {SnackBarOptions} options
     */
    show(options: SnackBarOptions): void

    /**
     * Dismisses any and all active Snackbars.
     */
    dismiss(): void
  }

  const instace: Snackbar

  export default instace
}
```

**Comment by hmajid2301** [comment]
I am also experiencing this, @VenancioAvila code fixes this problem.

**Comment by cooperka** [comment]
PR https://github.com/cooperka/react-native-snackbar/pull/111 has been merged to address the problem; please let me know if there are further issues.

**Pull request merged**
