### PR TITLE
Added Snackbar actions for android

### PR DESCRIPTION
**Pull request by PatKayongo**
Snackbar actions were included for ios, but not for android. This pull request adds these actions for android.

### CODE REVIEW

**Comment by cooperka** [comment]
Note: This was [originally opened on my fork](https://github.com/cooperka/react-native-snackbar/pull/1), which is the one the published npm module is fed from. Because it relies on unmerged changes, the change history is a bit messy here, but it can just be rebased once https://github.com/azendoo/react-native-snackbar/pull/4 is merged by @Liroo.

I've tested and verified @PatKayongo's changes on Android (and also iOS), it works great!

**Comment by cooperka** [comment]
This change is now [live on npm](https://www.npmjs.com/package/react-native-snackbar) as of [v0.2.1](https://github.com/cooperka/react-native-snackbar/releases) 😺

**Comment by Liroo** [comment]
Could you please rebase your work and we should be able to merge it @PatKayongo

**Comment by cooperka** [comment]
@PatKayongo the repo has just transferred ownership, and I reset `master` to reflect what's on npm. Your commit is already there as fb669928831a4cc52df8612b0ee27daf3ee3b027. Thanks again for contributing!

**Pull request merged**
