### PR TITLE
Default export instance instead of interface

### PR DESCRIPTION
**Pull request by rthomazel**
Fixes ts errors

### CODE REVIEW

**Comment by ghost** [comment]
This should be merged asap

**Comment by cooperka** [comment]
There seems to be ongoing debate in https://github.com/cooperka/react-native-snackbar/pull/106 as to whether this is broken or not. I'm a bit baffled, because it seems there should be one clear "right way" to do it.

I'm going to assume, based on popular opinion, that this PR is the right one. Please weigh in if you have other feedback. Thanks for submitting @Thomazella.

**Comment by slavikdenis** [comment]
Still don't get it, why `SnackBarOptions` is not be exposed... (usage: https://github.com/cooperka/react-native-snackbar/pull/106#issuecomment-500327893)

**Comment by cooperka** [comment]
@slavikdenis if you need further changes please feel free to submit a PR. I'd also appreciate documentation explaining why certain changes were needed, if you do submit something.

TypeScript + React integration has always seemed a bit sketchy to me, and this is clearly no exception!

**Comment by iRoachie** [comment]
Ha i was just about to send a PR and realised you all fixed it already. Thanks!

**Comment by iRoachie** [comment]
@slavikdenis Opened a PR to add in #116

**Comment by slavikdenis** [comment]
@iRoachie looks great to me :) https://github.com/iRoachie/react-native-snackbar/blob/fb8c6aac5697f6cd4c1e22d0dfdd261e9534beb2/src/index.d.ts#L25

**Pull request merged**
