### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by mahomahoxd**
Updated a few dependencies, also used implementation instead of compile as that is gradle 3's way of doing things. I didn't look a the "making the snackbar appear on top of everything", I'll try doing that in the upcoming days/weeks

### CODE REVIEW

**Comment by cooperka** [comment]
Hi @mahomahoxd, thanks for the PR -- to help me out, could you please explain the motivation for this change? e.g. why it's necessary. Sometimes upgrading dependencies like this can lead to incompatibilities with other projects. Thanks!

**Comment by mahomahoxd** [comment]
I noticed along with the libraries I was using with my app, I was getting multiple versions of build tools just to be able to compile and run the app. This was the main reason, I figured it was also "better" to keep the dependencies up to date as there might be improvements that could lead to better performance of the libraries and such. I've tested this locally, as in I've edited the package in node_modules and it seems to be working perfectly fine. You might wanna test it out more as I've had barely enough time to just test it once. I also liked gradle 3 as it seems its faster than previously but I'm not too sure. 

So a tl;dr, using multiple libraries that involve adjustments in the android part, will require different versions of build tools. If its just one library, I can live with that but it gets a bit weird if you have to download 5 different build tools for one project just to make it run y'kno ;)

**Comment by cooperka** [comment]
I looked into this a bit more and it seems like many libraries have standardized around build tools v25.0.2 (and associated dependencies). I don't think I want to change it here until there's a new standard, otherwise we'll just keep running into the same problem of projects having various different build tools versions.

Here's a quick way to standardize across all your dependencies. It goes in your app's `/android/build.gradle` and will cause all build tools versions to become v25.0.2:

```js
subprojects {
    afterEvaluate { Project project ->
        if (project.android) {
            android {
                compileSdkVersion 25
                buildToolsVersion "25.0.2"
            }
        }
    }
}
```

**Comment by cooperka** [comment]
I appreciate the PR though, thank you for being proactive about this! Let me know if you have any more questions. Cheers.

**Pull request closed without merging**
